### ISSUE TITLE
Add new Internship to the CZ

### ISSUE THREAD

**Issue by HimanshuNarware** [HimanshuNarware/CareerZunction_Intern#10]
Description

Add new Internship to the CZ

Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc24*

**Comment by guntarakesh** [comment]
@HimanshuNarware can i work on this issue ? 
and if yes , please explain me a little bit about this issue .

**Comment by 0plaze0** [comment]
Can you explain me the issue a bit more?
