### ISSUE TITLE
Add elitmus job portal in the internship section

### ISSUE THREAD

**Issue by Abhishek0732** [HimanshuNarware/CareerZunction_Intern#100]
Is your feature request related to a problem? Please describe.
I want to add another job portal elitmus in the internship section 

Describe the solution you'd like
Elitmus is the job portal for the freshers and experienced person and it also provide the job based on its ph test which elitmus conduct. 
** Add screenshot

Checklist
Example Fill x { [x] } into bracket

- [x ] I have checked the existing issues *
- [ x] I have read the Contributing Guidelines *
- [ ] I have starred the repository *
- [x ] Working under Gssoc24*

**Comment by PSS2134** [comment]
Can you explain it more clearly like how you going to do that! @Abhishek0732

**Comment by Abhishek0732** [comment]
elitmus is the platform which provide internship and job opportunity to the students and it also conduct ph test based on the scores many company hire. I am providing the link for your reference
https://www.elitmus.com/
I will add this in the internship section. Please assign it to me.

**Comment by PSS2134** [comment]
Ok you can go ahead! @Abhishek0732

**Comment by Abhishek0732** [comment]
I have made a pull request please check it
