### ISSUE TITLE
The UI of the documentation page does not look responsive.

### ISSUE THREAD

**Issue by piyush-gpt** [HimanshuNarware/CareerZunction_Intern#104]
**Describe the bug**

The UI of the documentation page does not look responsive. It badly affects user experience.

**Screenshots**

![Screenshot 2024-05-13 121726](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/122816988/dc526822-d5f0-4a87-8950-9deb84da167c)

![Screenshot 2024-05-13 122058](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/122816988/dcf3f9a6-e7e8-43ab-8683-1e01342a7de7)

I want to improve it so that it looks good in all devices.

Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc24*

**Comment by Suruchibharti** [comment]
hii ,
I'm GSSoC'24 contributor ,I want to work on this issue,
so, kindly requested to you to assign me the issue.
