### ISSUE TITLE
Center the content in the boxes

### ISSUE THREAD

**Issue by vinay02103** [HimanshuNarware/CareerZunction_Intern#110]
@HimanshuNarware
![Four Boxes ](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/140578491/b74054ee-cc24-4815-8849-b0080658a684)
 Issue:
I would like to set the content in all four boxes to center .

 Description:
Currently, the content in the boxes is aligned in diffrernt places .I propose that we modify the CSS to center the content within each box and add titles and descriptions to improve clarity and aesthetics.

**Comment by prateeksha17** [comment]
I request you to assign the above issue to me.

**Comment by PSS2134** [comment]
Actually, its already been raised here and assigned to someone #96
