### ISSUE TITLE
Adding Offline and Online buttons

### ISSUE THREAD

**Issue by veera6513** [HimanshuNarware/CareerZunction_Intern#114]
Is your feature request related to a problem? Please describe.
We can't be able to see selective internships. For example, if we want to see only offline internships then we don't have offline button.

Describe the solution you'd like
I will add two buttons in internship page (offline and online). if user clicks on offline then it will retrieve only offline internships.

** Add screenshot

Checklist
Example Fill x { [x] } into bracket

- [ x ] I have checked the existing issues *
- [ x ] I have read the Contributing Guidelines *
- [ x ] I have starred the repository *
- [ x ] Working under Gssoc24*

**Comment by veera6513** [comment]
please assign above issue to me

**Comment by PSS2134** [comment]
Its already raised here #105 , so you can work on different issues, I am closing this
