### ISSUE TITLE
Improve the About Us page

### ISSUE THREAD

**Issue by Anou25** [HimanshuNarware/CareerZunction_Intern#124]
The carts in about us page is not clearly visible due to the background and the text is not properly aligned.

Features:-
1) Adding hover effect to each cart can make it visible
2) The background image can be more blur
3) The contents in the cart can be properly aligned.

![Screenshot 2024-05-13 213509](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/136624807/b7b32a80-1afe-4325-aeb2-7f2e16618910)

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc24*

@HimanshuNarware please assign this task to me

**Comment by MonikaLuhach** [comment]
"About Us" section is vital for building a strong connection with our audience, differentiating our brand, and supporting our overall marketing and business goals. It plays a key role in making a lasting impression and driving engagement.

@HimanshuNarware I am happy to work on this issue under GSSoC 24 contribution. Could you please assign it to me?

**Comment by PSS2134** [comment]
Actually, this is already being raised #96  , you can work on other issues @Anou25
