### ISSUE TITLE
Enhancing the home page

### ISSUE THREAD

**Issue by Soumya6Tiwari** [HimanshuNarware/CareerZunction_Intern#128]
**Describe the bug**
The home page looks grammatically incorrect.

![image](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/117037441/f603067c-4790-4800-8280-b7698e30179b)
 removing the dots(.) after elevate ,your ,future

**Comment by Soumya6Tiwari** [comment]
@HimanshuNarware kindly assign me this issue under gssoc'24

**Comment by rawatji001** [comment]
@HimanshuNarware I want to work on this issue please assign it to me
![Uploading Screenshot from 2024-05-14 11-56-00.png…]()

**Comment by PSS2134** [comment]
Do that @Soumya6Tiwari

**Comment by PSS2134** [comment]
Mention your issue at PR you have created @Soumya6Tiwari

**Comment by Soumya6Tiwari** [comment]
@PSS2134  hmm done

**Comment by Soumya6Tiwari** [comment]
@PSS2134 

![Screenshot 2024-06-01 015151](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/117037441/0aa6e9a7-37f9-4cab-b350-ac829fcbe4e4)
here is the screenshot that you have not mentioned the label on my pull request even though it is merged . kindly be updated to the rules and norms of gssoc for marking down labels . Hoping you to rectify it asap
