### ISSUE TITLE
[BUG] QR Code Are Not Working as Not redirecting to CareerZunction GitHub Page

### ISSUE THREAD

**Issue by Ayush170803** [HimanshuNarware/CareerZunction_Intern#131]
QR Code are not redirecting to the GitHub Page for Starring⭐ the repository. So Kindly assign me this issue, so i can work towards it under GSSOC'24.
Thank You!!

![Screenshot 2024-05-14 105045](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/115927008/db96f257-da42-4577-8d94-ac134a31cc10)

Example  Fill x { [x] }  into  bracket

- [✅] I have checked the existing issues *
- [✅] I have read the Contributing Guidelines *
- [✅] I have starred the repository *
- [✅] Working under Gssoc24*

**Comment by anniepauline** [comment]
I'd love to work on it

**Comment by PSS2134** [comment]
I think it serves its purpose @Ayush170803 , so I am closing this
