### ISSUE TITLE
Alignment Issue in About Section

### ISSUE THREAD

**Issue by Prithwi32** [HimanshuNarware/CareerZunction_Intern#14]
**Describe the bug**
In the About section inside cards Images and texts are not properly aligned

**Expected behavior**
Proper alignment of components inside cards

**Screenshots**
![image](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/115262737/fc6ed9e0-f269-4e85-8c2f-4c3ef1263cce)

Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc24*

**Comment by Prithwi32** [comment]
@HimanshuNarware Please could you assign me this issue

**Comment by nishant0708** [comment]
hey i can fix this issue please assign it to me

**Comment by HimanshuNarware** [comment]
@Prithwi32  assigned U

**Comment by pandey079** [comment]
Pls assign it to me

**Comment by Prithwi32** [comment]
> @Prithwi32 assigned U

@HimanshuNarware I have done PR, please could check once

**Comment by root-0101** [comment]
Hey @HimanshuNarware the issue still exists, Please assign me this issue 

![Screenshot (80)](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/142779809/a4c24f66-24c5-41c7-950d-55d3d3180810)
**After Changes :**
![Screenshot (79)](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/142779809/8c0ded51-2ab0-4ebb-9377-c46c66e3223e)

**Comment by Prithwi32** [comment]
@HimanshuNarware gssoc tag is missing, please could add ..
