### ISSUE TITLE
 Website lacks responsiveness on various screen sizes

### ISSUE THREAD

**Issue by loginglug** [HimanshuNarware/CareerZunction_Intern#144]
QR code invisible on website due to responsiveness issue

To enhance page aesthetics and responsiveness, align QR code placement

Example  Fill x { [x] }  into  bracket

- [x ] I have checked the existing issues *
- [x ] I have read the Contributing Guidelines *
- [x ] I have starred the repository *
- [x ] Working under Gssoc24*

**Comment by PSS2134** [comment]
Can you share the screenshot to identify where the problem is @loginglug
