### ISSUE TITLE
updating the logo of twiiter

### ISSUE THREAD

**Issue by 20ankur07** [HimanshuNarware/CareerZunction_Intern#145]
@HimanshuNarware @Chaitali-sonare  Please let me update the logo of twitter to "X". please assign this issue to me

**Comment by anniepauline** [comment]
I'd love to work on it

**Comment by PSS2134** [comment]
You can do that @20ankur07 , from next time raise issue from proper issue template

**Comment by PSS2134** [comment]
Are you still on it ? @20ankur07

**Comment by 20ankur07** [comment]
> Are you still on it ? @20ankur07

i've completed it and created the pull request. please check

![Screenshot 2024-05-15 113006](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/125962231/124ea1aa-9cf2-4f02-aef2-413383f8dd21)
