### ISSUE TITLE
A little modification of text in the footer

### ISSUE THREAD

**Issue by sau-mili** [HimanshuNarware/CareerZunction_Intern#146]
Is your feature request related to a problem? Please describe.

Change "Star us" to "Rate us"

Describe the solution you'd like
Simply change the text and improve the on-hover CSS properties

** Add screenshot

![Screenshot 2024-05-14 202724](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/146661411/3b4fb3e3-e039-4731-a02d-ba5c788486c1)

Checklist
Example Fill x { [x] } into bracket

- [x ] I have checked the existing issues *
- [ x] I have read the Contributing Guidelines *
- [ x] I have starred the repository *
- [ x] Working under Gssoc24*

**Comment by anniepauline** [comment]
I'd love to work on it

**Comment by PSS2134** [comment]
Do that @sau-mili

**Comment by sau-mili** [comment]
I have made the changes and posted a pull request. please check. [#152 ](url)
