### ISSUE TITLE
Improving the hover effect on the Options(Boxes) in Internship Section

### ISSUE THREAD

**Issue by UjjwalGupta1105** [HimanshuNarware/CareerZunction_Intern#149]
The hover effect on the boxes can be very improved very much to improve the UI .

![GSSOC 4](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/165131091/e8915d7b-8a16-4d33-9e03-1c092f4f6bbd)

**Comment by anniepauline** [comment]
I'd love to work on this issue

**Comment by PSS2134** [comment]
Ok go ahead @UjjwalGupta1105
