### ISSUE TITLE
[Feature Request]: Theme Switch

### ISSUE THREAD

**Issue by rahul1841** [HimanshuNarware/CareerZunction_Intern#153]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Currently, our application lacks a feature of theme switching, limiting user customization options. Add a feature to switch between themes. The PR for this issue should address creating the following:
- A theme switching button
- White theme

- Dark Theme

### Use Case

Create and implement a theme toggle button and a dark theme for the website, allowing users to switch between three theme options: light, dark, and auto (device - theme). This toggle should dynamically adjust the color scheme and styling of various elements across the application based on the selected theme.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by PSS2134** [comment]
This issue is already created @rahul1841
