### ISSUE TITLE
[Bug]: Adding missing image links to the internship box

### ISSUE THREAD

**Issue by SadafKausar2025** [HimanshuNarware/CareerZunction_Intern#156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

the image of the some internship box was missing so I fixed it

### Expected behavior

it was not giving gook looking to the internship section and now after fixing all it's looks better

### Add ScreenShots

![Screenshot (1706)](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/137484958/9c7b9c40-9ab8-4715-b29e-53158240cba8)
![Screenshot (1707)](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/137484958/d0bd3a04-609f-40c0-a3b3-c3eecbf56fb9)
![Screenshot (1708)](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/137484958/8cf0ae6a-1783-403d-8f7f-d6ac9f0d2453)
![Screenshot (1709)](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/137484958/54d1fd26-bde7-4a19-88aa-1043046ff98b)
![Screenshot (1710)](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/137484958/0649ae14-304e-4a26-a218-6eccc528f17d)
![Screenshot (1711)](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/137484958/9f71abab-8569-4c27-9e67-f8a635ddb47c)
![Screenshot (1712)](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/137484958/46b70c77-9e0a-4856-9cf5-dc99765e0ace)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by SadafKausar2025** [comment]
I added image for
drivendata competition
goldman sach intern 
bharat pe
Google summer of search engine 
and many more missing images

**Comment by PSS2134** [comment]
You created a PR without raising an issue priorly, don't do that from next time @SadafKausar2025
