### ISSUE TITLE
Adding Scroll  to  Top button 

### ISSUE THREAD

**Issue by reshamsai150** [HimanshuNarware/CareerZunction_Intern#158]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add the  Scroll to top button feature on the website assign this issue to me @HimanshuNarware 

### Use Case

Instead of  manually scrolling all the way, the user can quickly return to the top of the  web page 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by PSS2134** [comment]
You can go ahead @reshamsai150 !
