### ISSUE TITLE
Text alignment in About Us section

### ISSUE THREAD

**Issue by SunayP** [HimanshuNarware/CareerZunction_Intern#161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

In About Us section, The text under “Around the Globe” is not aligned consistently with the other sections (“World’s Biggest,” “Open Source,” and “Free to use”). 
And the text is somewhat difficult to read due to the low contrast between the text and the background. 
![about us](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/157937147/4f47e6a9-b054-4c4c-a200-fd6504043f50)

### Use Case

To improve readability and visual consistency, ensure that all text sections are aligned properly, and due to dark text on a dark background does not provide enough visual distinction, which could lead to accessibility issues for users.

Please assign this issue to me, for further working on it.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Code-eat-sleep-include** [comment]
@PSS2134 Can you assign me this task?

**Comment by Harsha19-08** [comment]
can u assign me this issue as i well featured with Css and Tailwind styling

**Comment by Dhevamuthu** [comment]
Under GSSOC 24, Please assign the work to me!

**Comment by PSS2134** [comment]
its completed
