### ISSUE TITLE
[Feature Request]: Pagination for internship page

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [HimanshuNarware/CareerZunction_Intern#164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

There are many internship opportunities in the database. Scrolling down extensively negatively impacts the user experience. Therefore, I can create pagination for viewing internships.

### Use Case

By breaking down content into smaller, manageable parts, users can navigate through information more easily without feeling overwhelmed.

### Benefits

Users can quickly jump to specific sections of content, making it easier to find what they're looking for without excessive scrolling.

### Add ScreenShots

I like to design a pagination like below.

![image](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/139672976/ccf8c8ea-e6f3-43e1-9503-47ce6e39f6d6)

In the top i will display no of results showing out of total

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by DharshiBalasubramaniyam** [comment]
Hi @HimanshuNarware, please assign this issue to me.

**Comment by PSS2134** [comment]
Thats a great Idea, go ahead @DharshiBalasubramaniyam

**Comment by DharshiBalasubramaniyam** [comment]
Thank you for assigning me @PSS2134.

**Comment by mtg718** [comment]
please assign it to me  @PSS2134, under GSSoc'24
