### ISSUE TITLE
[Documentation Update]: Pull Request Template Creation

### ISSUE THREAD

**Issue by PradnyaGaitonde** [HimanshuNarware/CareerZunction_Intern#169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

I am writing to express my interest in contributing to your repository by creating a pull request template. 
I believe that having a standardized template will help streamline the contribution process, ensuring that all necessary information is included and making it easier for maintainers to review and merge pull requests. 
Could you please assign me the issue under gssoc24? I am excited about the opportunity to contribute to your project and help improve the workflow for all contributors.

### Suggested Change

I am writing to express my interest in contributing to your repository by creating a pull request template. 

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by PSS2134** [comment]
Yes, that , seems good @PradnyaGaitonde !
