### ISSUE TITLE
[Feature Request]: Adding Testimonials

### ISSUE THREAD

**Issue by sharmi4590** [HimanshuNarware/CareerZunction_Intern#170]
Hey @HimanshuNarware 
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Adding testimonials which is placed above the footer , always makes user experience much better and user always searches for reviews before use . So a pleasant testimonials will make the website much better.It will make the users to believe in the website as well. I will make sure the testimonials match your UI design.

### Use Case

This is my previous work regarding testimonials.
![Screenshot (387)](https://github.com/anuragverma108/SwapReads/assets/102676949/262e4eee-39c1-40ec-8b76-2e8b15f6fb84)
![Screenshot (388)](https://github.com/anuragverma108/SwapReads/assets/102676949/e0e924a3-82cd-450a-b89c-890966ca3eb4)
On placing cursor on each testimonial will flip it and show the review.

### Benefits

The user will get to know how many people got benefited from the website.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by spacedust26** [comment]
Hey @HimanshuNarware and @PSS2134 , I'd like to work on this issue under Gssoc'24 and design an apt testimonial section pertaining to the theme of the website

**Comment by PSS2134** [comment]
Ok you can do that @sharmi4590
