### ISSUE TITLE
[Feature Request]: Adding Back to top at documentation page

### ISSUE THREAD

**Issue by Scrapper700** [HimanshuNarware/CareerZunction_Intern#171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

A back to top button for better UI

### Use Case

Better UI

### Benefits

.

### Add ScreenShots

![Screenshot (222)](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/113296663/4e858e23-e965-4165-a9e9-ba4a0e82ac72)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Scrapper700** [comment]
@PSS2134 Please assign me this taks under Gssoc'24

**Comment by Scrapper700** [comment]
@PSS2134 please check this

**Comment by PSS2134** [comment]
This is already created here #158 @Scrapper700
