### ISSUE TITLE
[Styling]: Github icon color back to default while hovering

### ISSUE THREAD

**Issue by Scrapper700** [HimanshuNarware/CareerZunction_Intern#172]
Before:
![Screenshot (229)](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/113296663/4d7985f9-0ef2-4a63-af90-c4c4259bac59)

After:
![Screenshot (228)](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/113296663/f6f363bf-3fef-4c08-8e9e-7e94e3a4b884)

**Comment by Scrapper700** [comment]
@PSS2134 Can you assign me this task

**Comment by Code-eat-sleep-include** [comment]
@PSS2134 Could you please assign me this task!

**Comment by roushanverma23** [comment]
@HimanshuNarware please assign this task, I want to work on this
![gssoc](https://github.com/GameSphere-MultiPlayer/Squard-line/assets/137530796/bc19c5b1-a3c9-457f-b0f4-09e916b6b627)

**Comment by Hanshika248** [comment]
please assign me the task I would love to contribute to resolve the issue

**Comment by PSS2134** [comment]
Go Ahead @Scrapper700

**Comment by Chetanshinde123** [comment]
@PSS2134 Please assign this to me
