### ISSUE TITLE
Fixing the spelling of documetation to documentation

### ISSUE THREAD

**Issue by rajat99-default** [HimanshuNarware/CareerZunction_Intern#178]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Minor spelling mistake

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by rajat99-default** [comment]
@HimanshuNarware assign kardo fir wishlist wala iske baad merge karuga

**Comment by Hanshika248** [comment]
Please assign the task I would love to contribute to resolve the issue
