### ISSUE TITLE
[Feature Request]: Theme changeable

### ISSUE THREAD

**Issue by anshkie** [HimanshuNarware/CareerZunction_Intern#186]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The overall website is only in dark mode. I think changing the website theme according to the user can enhance the overall user experience for this website. 

### Use Case

Themes are very common feature of almost any website. Providing this feature can be beneficial for the website

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by anshkie** [comment]
@HimanshuNarware Please assign this job to me ,I can do really good work in this

**Comment by PSS2134** [comment]
Its already been created, so closing this as of now
