### ISSUE TITLE
Enhancing User Experience: Introducing Light Theme Feature

### ISSUE THREAD

**Issue by Karthikreddy0165** [HimanshuNarware/CareerZunction_Intern#19]
Problem:
Many users prefer using websites with light themes for better readability, especially in well-lit environments. However, our website currently lacks a light theme option, which can be inconvenient for users who prefer lighter interfaces.

Solution:
Implement a light theme feature for the website to enhance user experience and accessibility. The light theme should offer a visually pleasing alternative to the existing dark theme, providing users with the flexibility to choose their preferred browsing experience.

Requested Changes:

Introduce a light theme option in the website .

Ensure that all UI elements, including text, backgrounds, and buttons, are appropriately styled for the light theme.
Provide a seamless toggle between the light and dark themes, allowing users to switch between them easily.

basic demo at url :
https://github.com/HimanshuNarware/CareerZunction_Intern/assets/148652342/4c7d9696-c7d0-4f84-b7db-8c312e3ad4e9

Benefits:

Enhances accessibility for users who prefer lighter interfaces.
Improves overall user experience and satisfaction.
Demonstrates our commitment to inclusivity and user-centric design principles.

Checklist:

[yes] I have checked the existing issues.
[yes] I have read the Contributing Guidelines.
[yes] I have starred the repository.
[yes] Working under GSSOC24.

**Comment by Karthikreddy0165** [comment]
please assign me this issue.

**Comment by ANSH127** [comment]
@HimanshuNarware  assign to me I'll do it
