### ISSUE TITLE
hover effect on what is opensource page

### ISSUE THREAD

**Issue by thesri** [HimanshuNarware/CareerZunction_Intern#20]
**Describe the bug**
hover effect on what is opensource page is missing , the articles etc, have this box hover, making it text hover would improve its ui

**Expected behavior**
box hover in pink border
**Screenshots**

Example  Fill x { [x] }  into  bracket

- [✔ ] I have checked the existing issues *
- [ ✔] I have read the Contributing Guidelines *
- [ ✔] I have starred the repository *
- [ ✔] Working under Gssoc24*

**Comment by HimanshuNarware** [comment]
@thesri  share a screenshot

**Comment by thesri** [comment]
> @thesri share a screenshot

![WhatsApp Image 2024-05-10 at 11 41 20_8d5ef970](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/98333833/f9115189-416a-4359-bcfc-a371a363e20c)
couldnt get a normal ss cause it wasnt a normal hover.

**Comment by HimanshuNarware** [comment]
@thesri It is not CZ page it just on the blog on Open-source
