### ISSUE TITLE
[Feature Request]:  Add copyright details section

### ISSUE THREAD

**Issue by Saimanjari777** [HimanshuNarware/CareerZunction_Intern#201]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey, @HimanshuNarware I would like to add the copyright details section in the footer section.

### Use Case

I would like to ass the copyright details which is important as it helps to protect the value of an author/academic/researchers work, by giving the originator of the work the ability to protect it from unlicensed or uncredited usage.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by roushanverma23** [comment]
@HimanshuNarware please assign this task, I want to work on this
![gssoc](https://github.com/GameSphere-MultiPlayer/Squard-line/assets/137530796/bc19c5b1-a3c9-457f-b0f4-09e916b6b627)

**Comment by 22-0304** [comment]
Can you assign me this issue @HimanshuNarware

**Comment by PSS2134** [comment]
Ok @Saimanjari777

**Comment by roushanverma23** [comment]
Hii @PSS2134 i have requested first to assign this issue ?
