### ISSUE TITLE
[Feature Request]: Adding Icons tin the Navbar

### ISSUE THREAD

**Issue by SadafKausar2025** [HimanshuNarware/CareerZunction_Intern#203]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add the features to add icons in the Navbar links

### Use Case

it look beautiful and realistic to the page

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by SadafKausar2025** [comment]
Hi @HimanshuNarware 
Can you please assign me this issue #203?

**Comment by PSS2134** [comment]
This issue is already being worked upon @SadafKausar2025
