### ISSUE TITLE
[Feature Request]: Anchoring tag enhancement in navbar

### ISSUE THREAD

**Issue by harikasayani** [HimanshuNarware/CareerZunction_Intern#207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to enhance the anchoring tags in navbar.

### Use Case

Navbar becomes attractive.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by nhyadav05** [comment]
assign me this issue under gssoc24

**Comment by PSS2134** [comment]
add some screenshots @harikasayani

**Comment by harikasayani** [comment]
Hi @PSS2134 
I want to do it like this.

https://github.com/HimanshuNarware/CareerZunction_Intern/assets/143275265/6e89dd16-af62-43e5-b931-b54194952625

**Comment by PSS2134** [comment]
@HimanshuNarware

**Comment by HimanshuNarware** [comment]
@PSS2134 someone is already working on same issue #162
