### ISSUE TITLE
[Feature Request]: Add testimonials section to the home page

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [HimanshuNarware/CareerZunction_Intern#215]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Currently, In the home page we have the hero section, about us section and the footer. I would like to add a testimonials section (What our client says). 

### Use Case

- Highlight individuals who successfully found jobs through the platform.
- Showcase users who advanced their careers with the site's resources and guidance.
- Include feedback from users who benefited from specific services.

### Add ScreenShots

The section will be as below.

![image](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/139672976/6879faf2-0557-4a87-ba52-09535ce5e20c)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by PSS2134** [comment]
This issue already been created @DharshiBalasubramaniyam
