### ISSUE TITLE
About heading font is not good

### ISSUE THREAD

**Issue by venkatasai24** [HimanshuNarware/CareerZunction_Intern#22]

**Comment by HimanshuNarware** [comment]
@venkatasai24 Share a Screenshot

**Comment by venkatasai24** [comment]
Yeah, here is the screenshot you asked for  

@HimanshuNarware 


As we can see the font of remaining sub headings are much better than the main heading..

![image](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/103911586/ddaaa19e-ffe1-4e55-9573-e611a74d6f56)



I request you to assign it to me!!

**Comment by venkatasai24** [comment]
@HimanshuNarware  Also, on the documentation page, the font is bad and the font size of 'step'  is not appropriate!!

![image](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/103911586/32b5886d-5952-4f66-85b9-3c0e5068e5e8)

**Comment by HimanshuNarware** [comment]
@venkatasai24  ok start working on that

**Comment by venkatasai24** [comment]
yeah ,completed it,pls review the pull request I made @HimanshuNarware

**Comment by Shilpajha29** [comment]
@venkatasai24 Kindly assign this task to me
