### ISSUE TITLE
[Feature Request] : implement the Dark & Light mode 

### ISSUE THREAD

**Issue by sivaprasath2004** [HimanshuNarware/CareerZunction_Intern#220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

- In this project only available on dark we will custom mode not available.
- If i can implement the dark & light mode .

### Use Case

- User can easy to change our custom mode change and with our choice.

### Benefits

- Attractive and more users can be used.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by PSS2134** [comment]
This is already been worked upon
