### ISSUE TITLE
Updating Learn.md file

### ISSUE THREAD

**Issue by CoderGirl2844** [HimanshuNarware/CareerZunction_Intern#224]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

In Learn.md file, under introduction section the link given to open CZ intern website is not working  
It's important to solve this issue as learn.md file gives a brief overview about the project, and it helps the new contributors to begin contributing to this project

### Suggested Change

I will replace the link with a working one ..
Please assign this issue to me 

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by CoderGirl2844** [comment]
please assign the gssoc and level lable @PSS2134

**Comment by PSS2134** [comment]
can you add the screenshot of section you talking about ? @CoderGirl2844

**Comment by PSS2134** [comment]
Actually, that link is correct, it's meant after cloning this repo, and to see the running of the app, you need to visit that localhost:3000. @CoderGirl2844
