### ISSUE TITLE
Faulty Social Media Links 

### ISSUE THREAD

**Issue by Suvam3456** [HimanshuNarware/CareerZunction_Intern#27]
Hello PA,
The Social media links at the bottom in the footer is not working .

I can fix them and can add more social media icons as well if you specify.

![image](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/99579881/c56b5963-2ed2-4c31-b692-fef5f70e455d)

@HimanshuNarware Please assign me this issue under GSSOC'24.

**Comment by Suvam3456** [comment]
You can add labels on this issue .

**Comment by Shilpajha29** [comment]
@HimanshuNarware kindly assign this task to me

**Comment by Suvam3456** [comment]
Hey @HimanshuNarware , I raised the PR

**Comment by Suvam3456** [comment]
@HimanshuNarware Please add label of GSSOC'24 in this issue.
