### ISSUE TITLE
[Bug]: Adding Missing Images to some of the Internships

### ISSUE THREAD

**Issue by SadafKausar2025** [HimanshuNarware/CareerZunction_Intern#276]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

some of the internship is not having any images or images are invalid

### Expected behavior

it is not looking good while scrolling through the intrnships

### Add ScreenShots

![Screenshot (1849)](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/137484958/d5d93862-cd21-4f16-a920-c411520fadbe)

![Screenshot (1847)](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/137484958/084375ab-a109-44b3-9a52-9a3a4d133ca6)

![Screenshot (1848)](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/137484958/840295e9-3d16-404e-b8a9-2079a06fc560)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by SadafKausar2025** [comment]
hello @HimanshuNarware 
can you please assign me this issue?

**Comment by Shubh942** [comment]
Good Luck
