### ISSUE TITLE
Nav Bar visibility 

### ISSUE THREAD

**Issue by aanchalpahuja18** [HimanshuNarware/CareerZunction_Intern#29]
![image](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/136963878/f7889c0a-e39a-4ba2-a4f6-a726805e8717)

Enhancing the font colour and hovering effect in navbar will help in improving the UI of the website

**Comment by aanchalpahuja18** [comment]
Kindly assign me this issue

**Comment by divyansh141** [comment]
Kindly assign me this issue under GSSOC'24

**Comment by R1MO9** [comment]
I CAN DO THIS ASSIGN ME

**Comment by aakrati14** [comment]
Enhancing the font color and hovering effect in navbar will help in improving the UI of the website. I am eager to take on this task of improving our website's navigation bar to ensure responsiveness across all devices. Additionally, I'll focus on improving the hover effects of the navbar. This will improve the user experience and contribute positively to our website's overall aesthetics. Please assign me this task, and I'll work diligently to make valuable contributions.

-I have checked the existing issues *
-I have read the Contributing Guidelines *
-I have starred the repository *
-Working under Gssoc24*

**Comment by R1MO9** [comment]
@Chaitali-sonare assign me

**Comment by HimanshuNarware** [comment]
@divyansh141 @aanchalpahuja18  someone is already working on this
