### ISSUE TITLE
Footer correction and overall design fix

### ISSUE THREAD

**Issue by Annu117** [HimanshuNarware/CareerZunction_Intern#290]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The footer looks like an element; there shouldn't be an extra background after the footer ends. The arrow placement needs to be fixed. Social media icons have different hover effects, can be made similar with better interactions.

The navbar spacing is large. It should be made standard. It covers most of the page.
The About Us section is static. Hover interactions can be added.

### Expected behavior

Improve overall homepage design.

### Add ScreenShots

![image](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/108427028/25534cfb-75b6-44e0-8d1d-357e5f7db764)

![image](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/108427028/0b89e541-0584-4951-8cd7-0386d10a1ec9)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by nileshsn** [comment]
@HimanshuNarware Assign me under gssoc24

**Comment by PSS2134** [comment]
Ok go ahead @Annu117
