### ISSUE TITLE
Correct the typo error on the website

### ISSUE THREAD

**Issue by HimanshuNarware** [HimanshuNarware/CareerZunction_Intern#3]

**Comment by Packjackisback** [comment]
What is the typo?

**Comment by Packjackisback** [comment]
Oh :skull:

**Comment by Packjackisback** [comment]
Should all be fixed in my pr. seeking approval

**Comment by HimanshuNarware** [comment]
> What is the typo?

are you working under Gssoc'24

**Comment by HimanshuNarware** [comment]
> What is the typo?

spelling mistakes

**Comment by HimanshuNarware** [comment]
@Packjackisback  then first registered for it
link https://gssoc.girlscript.tech/project

**Comment by Packjackisback** [comment]
Nah, I'm good

**Comment by Karthikreddy0165** [comment]
I understood the issue can I  solve it. I am gssoc contributor

**Comment by nishant0708** [comment]
hey @HimanshuNarware  i can fix this please assign it to me

**Comment by Packjackisback** [comment]
i mean my pr works
