### ISSUE TITLE
[Bug]: Change Twitter logo in footer.

### ISSUE THREAD

**Issue by zalabhavy** [HimanshuNarware/CareerZunction_Intern#319]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Replace Twitter icon to new logo X.

### Expected behavior

New Logo should be use in footer.

### Add ScreenShots

![image](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/126322584/47359e8d-9ea0-4014-8793-a3875459ae05)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Shubh942** [comment]
I think this issue is already assigned to another contributor.
You can work on another issue, ping me for assigning the one.

**Comment by zalabhavy** [comment]
Done @Shubh942

**Comment by Tanishka023** [comment]
Hey there!! I can fix this issue easily, please assign this to me under GSSoC'24
