### ISSUE TITLE
Redesigning the About us section(Aligning the icons and more)

### ISSUE THREAD

**Issue by anuza08** [HimanshuNarware/CareerZunction_Intern#32]

**Comment by R1MO9** [comment]
assign this to me and mention the level

**Comment by HimanshuNarware** [comment]
@anuza08  how you going to redesign the page , show some designs

**Comment by Hemashree21** [comment]
@HimanshuNarware please assign this issue to me. I will make the About Us section look visually appealing and add animation and hovering effects that align to the color template of the project. I have attached the sample below.

![image](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/138188163/9ccc8a1d-46c5-421a-aa97-177ba9a0cb7b)

**Comment by pahuja-sahil** [comment]
hello @HimanshuNarware. I kindly request you to assign this issue to me under GGSoC'24. I have built a blogging website whose link is given below, kindly see it and give me permission to contribute towards your project.
link - https://github.com/pahuja-sahil/Online-Blogging-System.
Thank you.

**Comment by anuza08** [comment]
> @anuza08 how you going to redesign the page , show some designs

![Screenshot 2024-05-14 000340](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/98256478/7c676685-1531-44db-83c0-5c8cafee8aa3)
this is my design , if there are any changes to be made pls let me know

**Comment by nhyadav05** [comment]
assign me this issue under gssoc24

**Comment by Yuvraj960** [comment]
@HimanshuNarware Please assign this issue to me under GSSoC24. I will do this work very effeciently

**Comment by Vin205** [comment]
Please assign me this issue

**Comment by Chetanshinde123** [comment]
@anuza08 Is issue still open.
Please assign this to me I will improve it.

**Comment by shashbh18** [comment]
please assign this to me.
