### ISSUE TITLE
[Bug]: Contact  submit button not show message after click on submit

### ISSUE THREAD

**Issue by zalabhavy** [HimanshuNarware/CareerZunction_Intern#322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When submit form it should show message.

### Expected behavior

When anyone click submit after fill detail message shown Thank you we will connect soon !

### Add ScreenShots

![image](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/126322584/9ba5709f-f6c3-4eb6-b607-a1b99783e2a9)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by zalabhavy** [comment]
@Shubh942 Please assign me this !!

**Comment by Shubh942** [comment]
Good luck.
