### ISSUE TITLE
Testimonial section

### ISSUE THREAD

**Issue by paulkrishanu4** [HimanshuNarware/CareerZunction_Intern#329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

want to add a testimonial section in home page featuring students those who bagged internship offer from this website.
Testimonial section will be displayed as a slideshow manner where cards will move from left to right.

### Use Case

![Screenshot_10-6-2024_222843_www brainwareuniversity ac in](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/169196836/9282edcb-c4b1-4f5b-856d-c64758f2137b)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by HimanshuNarware** [comment]
@paulkrishanu4  someone already working on this
