### ISSUE TITLE
Navbar enhancement

### ISSUE THREAD

**Issue by H1mang1** [HimanshuNarware/CareerZunction_Intern#33]
Adding better hover effects on the navbar and also making the navbar responsive on all devices. I am eager to take on this task of improving our website's navigation bar to ensure responsiveness across all devices. Additionally, I'll focus on improving the hover effects of the navbar. This will improve the user experience and contribute positively to our website's overall aesthetics.  Please assign me this task, and I'll work diligently to make valuable contributions.

-  I have checked the existing issues *
-  I have read the Contributing Guidelines *
- I have starred the repository *
- Working under Gssoc24*

**Comment by H1mang1** [comment]
Thank you so much.

**Comment by Chaitali-sonare** [comment]
https://www.linkedin.com/in/himanshunarware/

**Comment by PSS2134** [comment]
I have merged this
