### ISSUE TITLE
[style:] Enhance background color

### ISSUE THREAD

**Issue by root-0101** [HimanshuNarware/CareerZunction_Intern#358]
As of now the background color is too dark which affects some section of the page. so, it would be great if we can improve this which is also great for the user experience.

**Comment by krishna25092005** [comment]
I would like to work on this project. Please assign it to me.

**Comment by illusion1412** [comment]
please assign me this issue. I have worked on design projects. So, I have a good relationship with colors.

**Comment by crazyshrut** [comment]
hey @illusion1412, @HimanshuNarware  assign this issue to me.
I know how to make it work.
