### ISSUE TITLE
[style:] Modify the apply now button

### ISSUE THREAD

**Issue by root-0101** [HimanshuNarware/CareerZunction_Intern#359]
the current button style is not great, modify the button style will enhance the users experience and also improve the overall UI

![Screenshot 2024-06-13 210253](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/142779809/bc914f8b-3e0d-4805-b8f3-fcb65f5db572)

**Comment by HimanshuNarware** [comment]
@root-0101  someone already working on this
