### ISSUE TITLE
Add a login page

### ISSUE THREAD

**Issue by Pranav-Rastogi1** [HimanshuNarware/CareerZunction_Intern#37]
Is your feature request related to a problem? Please describe.
adding a sign up page is always a plus point .

Describe the solution you'd like

Adding the signup /login page to the user

** Add screenshot

Checklist
Example Fill x { [x] } into bracket

- [ x] I have checked the existing issues *
- [ x] I have read the Contributing Guidelines *
- [x ] I have starred the repository *
- [x ] Working under Gssoc24*

**Comment by Syed0206** [comment]
@HimanshuNarware Please assign me this issue under GSSOC'24

**Comment by FatemaBaig** [comment]
Hello sir,
i would like to work on this project. Please assign it to me under GSSOC-24

**Comment by R1MO9** [comment]
Assign this to me , i can handle this **effectively**

**Comment by DevNandini02** [comment]
I have recently learned how to make login and signup pages. for a website. Please give me a chance to apply my knowledge to this task.

Please assign this task to me under GSSoC '24.

**Comment by R1MO9** [comment]
@Chaitali-sonare assign me

**Comment by IkramBagban** [comment]
Hello @HimanshuNarware,

I am interested in contributing to the CareerZunction_Intern project, specifically in adding the login page as described in issue #37. I have experience with web development technologies that I believe will be beneficial for this task.

Could you please assign this issue to me under GSSoC '24.? I'm eager to start working on it and contribute to the project.

Thank you!

**Comment by ShrestyTyagi** [comment]
Describe:
I would like to add a login page. It will have option of signin and signup where the user have to enter the username and password.
I would like to work on this issue. Please assign this issue to me. @HimanshuNarware

**Comment by saswat733** [comment]
i would make login page more pleasing to watch . i will make sure that whole process is secured and encrypted

**Comment by drick-infinity** [comment]
I did this in above PR 
plz review this

**Comment by IkramBagban** [comment]
Hello @Chaitali-sonare  and @HimanshuNarware ,

I have made a pull request for the new login page, as mentioned in issue #37. This page matches the existing color theme and I've also added a login route. When you click on the login button, it will display input values in the console.

Could you please review my pull request and merge it if everything looks good? Thank you for your time!

**Comment by IkramBagban** [comment]
Please assign this to me and then merge. @Chaitali-sonare  @HimanshuNarware

**Comment by HimanshuNarware** [comment]
@saswat733 @IkramBagban @drick-infinity @R1MO9  already someone is working on this issue.
