### ISSUE TITLE
[Bug]: Proper margins in contact page.

### ISSUE THREAD

**Issue by zalabhavy** [HimanshuNarware/CareerZunction_Intern#377]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There is no margins in input filed.

### Expected behavior

there should be proper margin bottom.

### Add ScreenShots

![image](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/126322584/9f5f7176-a9c0-4a8e-9821-1671bc477f72)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by zalabhavy** [comment]
@Shubh942 Please assign me this task !

**Comment by Shubh942** [comment]
Good luck!
