### ISSUE TITLE
✨ [Feature Request]:  Implement "Scroll Down Progress Bar"

### ISSUE THREAD

**Issue by MastanSayyad** [HimanshuNarware/CareerZunction_Intern#384]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @HimanshuNarware and @Shubh942 

I would like to suggest adding a scroll down progress bar to the website to enhance user experience. 

### Use Case

- A scroll progress bar visually indicates how much of the page has been scrolled and how much is left, providing users with a better sense of their position on the page. 
- This feature can be especially helpful for long pages blogs, docs, and articles.

### Benefits

- Enhances user experience by providing visual feedback.
- Useful for long pages or articles.
- Improves overall navigation and user satisfaction
- Looks more engaging.

### Add ScreenShots

like this

![image](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/101971980/1039a5ad-67cf-4dc5-aeb0-8202610c683f)

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MastanSayyad** [comment]
@HimanshuNarware and @Shubh942 please assign me this issue under gssoc.

**Comment by PSS2134** [comment]
Looks good @MastanSayyad
