### ISSUE TITLE
[Bug]: bottom to top button is not working

### ISSUE THREAD

**Issue by SrinivasDevolper** [HimanshuNarware/CareerZunction_Intern#397]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The button is not visible when going down the website page

### Expected behavior

The button should be visible when going down the website page

### Add ScreenShots

https://github.com/HimanshuNarware/CareerZunction_Intern/assets/121508628/49b64c68-3fd3-428c-a278-8daf09529a59

**I am GSSOC24 Contributor
Please assign me, I would like to work on it**

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by HimanshuNarware** [comment]
@SrinivasDevolper someone already working on the this issue
