### ISSUE TITLE
[Feature Request]: add the login/signup option in nav bar

### ISSUE THREAD

**Issue by CoderGirl2844** [HimanshuNarware/CareerZunction_Intern#400]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

a login/signup page will allow users to create their account and attach their resumes accordingly so that they will be notified whenever new internships are updated

### Use Case

the login page will allow users to create an account and they will be notified every time an internship opportunity is updated.
please assign me this issue

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by HimanshuNarware** [comment]
@CoderGirl2844  someone already working the same issues
