### ISSUE TITLE
[Feature Request]: Update hover effect of footer

### ISSUE THREAD

**Issue by heli0707** [HimanshuNarware/CareerZunction_Intern#406]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

To improve the footer hover effect, make it visually appealing by adding smooth color changes and animations. This creates a more engaging and interactive experience when users move their mouse over the footer elements.

https://github.com/HimanshuNarware/CareerZunction_Intern/assets/95361125/97a12fff-b923-407f-a2ef-c4453a4c5b79

Assign this issue to me!

### Use Case

A use case for improving the footer hover effect is enhancing user engagement and satisfaction on a website. When users hover over footer links, smooth color changes and animations can make the site feel more interactive and polished, encouraging them to explore more content.,

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by jayanththalla** [comment]
please assign me@pa
