### ISSUE TITLE
[Feature Request]: Add Subscribe to our NewsLetter feature

### ISSUE THREAD

**Issue by AfrozeSVU** [HimanshuNarware/CareerZunction_Intern#409]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

@HimanshuNarware 
Subscribe to our Newsletter feature can be added in footer

### Use Case

In footer subscribe to newsletter feature adds up to connect with the updates from the site .Please assign me this issue

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [x] I have starred the repository

**Comment by riteshjha61253** [comment]
@PSS2134 I want to work on this issue can you please assign it to me?

**Comment by PSS2134** [comment]
Since @AfrozeSVU is not active , I am assigning it to @riteshjha61253
