### ISSUE TITLE
[Feature Request]: Send mail on contact form submission

### ISSUE THREAD

**Issue by Ayesha-Siddiqua88** [HimanshuNarware/CareerZunction_Intern#410]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to implement a feature where mail is sent to the owner when user submits the contact form. This will be implemented using emailjs. The mail will include the details of the user which where filled in contact form. This will improve user experience.

### Use Case

Implementing email functionality for the contact form will enhance the project by ensuring timely communication, improving user engagement, and streamlining the handling of user queries and feedback.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by PSS2134** [comment]
Go Ahead @Ayesha-Siddiqua88 !
