### ISSUE TITLE
[Bug]: Re-Create and Enhance the Cursor Trail effect 

### ISSUE THREAD

**Issue by MastanSayyad** [HimanshuNarware/CareerZunction_Intern#424]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hey @PSS2134 

I would like to recreate the cursor trail effect to the website matching to the website design theme as the current one is looking so bad and is not user friendly at all

### Expected behavior

I am going to Re-Create the Cursor trail effect and make it work smooth and faster than the current one, it will not disperce instead it will follow the path movement of the cursor 

### Add ScreenShots

**Like This:** (These are my previous works)

https://github.com/user-attachments/assets/841dd647-f990-43c9-b317-2cff2f3f54d1

https://github.com/SUGAM-ARORA/UniCollab/assets/101971980/8fbcf113-1885-4d6e-a90c-628e269d2572

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by PSS2134** [comment]
can you try out some different cursor themes as well, other than these
