### ISSUE TITLE
[Bug]:      

### ISSUE THREAD

**Issue by theeayushkumar** [HimanshuNarware/CareerZunction_Intern#431]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

See the screenshots i have shared
The "CareerZunction" section is on the left side.
The "Documentation" section is centered.
The "License" section is on the right side.
The QR code and social media links are at the bottom.

### Expected behavior

Use Flexbox or CSS Grid: These CSS layout modules can help align and distribute the space among items in a container.

Ensure Consistent Padding and Margins: Make sure that all sections have consistent padding and margins to maintain alignment.

Check for Floating Elements: Ensure there are no floating elements that could disrupt the layout.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/15aaaafc-dc8a-4cdc-be71-ac5508be7db3)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by PSS2134** [comment]
Please refer to the main link of website @theeayushkumar
