### ISSUE TITLE
LOGO MISSING in TITLE BAR

### ISSUE THREAD

**Issue by anshgautam-github** [HimanshuNarware/CareerZunction_Intern#44]
Is your feature request related to a problem? Please describe.
In the below picture, u can see the logo of React is coming in the title bar which is not looking professional.

Describe the solution you'd like
I can insert the logo of the website, in the title section that will look more professional.

** Add screenshot
![image](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/95379812/b9374430-05f3-4ca8-b4cf-4c00b6af8244)

Checklist
Example Fill x { [x] } into bracket

- [x ] I have checked the existing issues *
- [ x] I have read the Contributing Guidelines *
- [ x] I have starred the repository *
- [ x] Working under Gssoc24*

Kindly , assign this issue to me

**Comment by pandeyji711** [comment]
Hello @HimanshuNarware 

I've noticed an issue with the website that I believe I can fix. Replacing the default React logo with a custom logo that represents your website can indeed give it a more polished and branded look.
  I have checked the existing issues 
  I have read the Contributing Guidelines 
  I have starred the repository 
 Could you please assign this issue to me for contribution under GSSoC'24.

**Comment by Shilpajha29** [comment]
@HimanshuNarware kindly assign this task to me

**Comment by IkramBagban** [comment]
Hello @HimanshuNarware,

I am eager to address the issue of the missing logo in the title bar as described in issue #44. I believe my skills in web design and graphic integration can help quickly resolve this.

Could you please assign this issue to me under GSSOC'24? I'm ready to start working on this and look forward to contributing to the project.

Thank you!

**Comment by utkarsh2023021** [comment]
I believe I can effectively tackle this issue and contribute positively to the project. Could you kindly assign the "LOGO MISSING in TITLE BAR" issue to me? I am eager to start working on it and collaborate on it , kindly assign this project to me.

**Comment by HimanshuNarware** [comment]
@anshgautam-github someone is already working on this
