### ISSUE TITLE
Want to add a new program 

### ISSUE THREAD

**Issue by anshgautam-github** [HimanshuNarware/CareerZunction_Intern#46]
Description
Want to add DEVELOP for GOOD progam in the list 

Example  Fill x { [x] }  into  bracket

- [ x] I have checked the existing issues *
- [ x] I have read the Contributing Guidelines *
- [ x] I have starred the repository *
- [ x] Working under Gssoc24*

Kindly, assign it to me under GSSOC

**Comment by veera6513** [comment]
Could please explain bit more about the requirement and what needs to be done.

**Comment by HimanshuNarware** [comment]
@anshgautam-github  can you explain me

**Comment by anshgautam-github** [comment]
@HimanshuNarware  Develop for Good powers social good through students from all colleges and backgrounds. They prioritize making its valuable, hands-on project experiences accessible to underserved and underrepresented students in tech to accelerate their careers. It strives to empower the next generation of diverse tech leaders to learn by doing good, all while furthering the digital transformation of the nonprofit sector. At its core, Develop for Good hopes to create a world where students, nonprofits, and corporations are dedicated to furthering technical education, advancing digital equity, and helping one another unlock their fullest potential.
