### ISSUE TITLE
[Feature Request]: Testimonials not showing in mobile

### ISSUE THREAD

**Issue by komal-agarwal5** [HimanshuNarware/CareerZunction_Intern#468]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

In mobile view the Testimonials under blog is not showing

### Use Case

I want to fix this

### Add ScreenShots

![WhatsApp Image 2024-07-24 at 00 01 57_60983d32](https://github.com/user-attachments/assets/02a4bfab-b1f8-4663-a175-66c44a1b1e0e)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Anurag-Gaiwal** [comment]
Is it resolved? , I am able to see the testinmonials on mobile view, should I work on it or no?
