### ISSUE TITLE
slid bar not responding!!

### ISSUE THREAD

**Issue by pandeyji711** [HimanshuNarware/CareerZunction_Intern#47]
slidbar at home page is not responding on click  

- [X ] I have checked the existing issues *
- [ X] I have read the Contributing Guidelines *
- [X ] I have starred the repository *
- [X ] Working under Gssoc24*

**Comment by spacedust26** [comment]
Hey! @HimanshuNarware ! Kindly assign this issue to me. I'd like to design an attractive scroll bar for the website. I am well versed in the required tech stack for the same. Thank you.

**Comment by pandeyji711** [comment]
nav bar still not fixed please assign this issue to me
