### ISSUE TITLE
[New Internship/Hackathon]: Add Sparkthon hackathon by walmart

### ISSUE THREAD

**Issue by zalabhavy** [HimanshuNarware/CareerZunction_Intern#470]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I will add all information about this hackathon.

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by mohitxd-fr** [comment]
can you please assign me this issue?
