### ISSUE TITLE
Add Icons to Navbar 

### ISSUE THREAD

**Issue by sailaja-adapa** [HimanshuNarware/CareerZunction_Intern#471]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hello Project Admin
I would like to add icons to Navbar
Can you assign me this issue under GSSOC'24

![IMG_20240724_141721](https://github.com/user-attachments/assets/d113ca6c-6c52-455e-b2c8-4e202079473c)

### Use Case

It will make our website to look Attractive 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by PSS2134** [comment]
I think adding icons will make it messy, as we dont have much space, you can work on other issues @sailaja-adapa
