### ISSUE TITLE
Add a Rate Us Option 

### ISSUE THREAD

**Issue by sailaja-adapa** [HimanshuNarware/CareerZunction_Intern#472]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hello Mam, my name is A.A.D.Sailaja. I am a Tech Enthusiastic and i'm looking forward to contribute in open source projects. Here in this project i seen a issue about the position of Blogzen above the search box it is not perfectly positioned at center. Once please go through that.

Can you please assign me this issue under gssoc'24

### Use Case

It will Enhance User Experience 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by PSS2134** [comment]
Can you add a screenshot, also please use main link of website, not the testing one for reference @sailaja-adapa

**Comment by sailaja-adapa** [comment]
![IMG_20240706_122058](https://github.com/user-attachments/assets/979952b1-8d10-4e86-8ca6-24eb02f9ddc3)

**Comment by PSS2134** [comment]
Actually this is already present in feedback page @sailaja-adapa , You can work on other issues
