### ISSUE TITLE
[Feature Request]: Re-Create and Enhance The Contributors Page

### ISSUE THREAD

**Issue by MastanSayyad** [HimanshuNarware/CareerZunction_Intern#476]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @PSS2134 

I would like to enhance and fix the current contributors page as it is not look good with the current design theme of the website

![image](https://github.com/user-attachments/assets/68f44e58-0526-4c61-85de-b7f9d73e1d39)

also, the multiple cards do not look good on the page, also it does not reflect all contributors list 

- I would like to create and enhance the page like this:

![image](https://github.com/user-attachments/assets/969d1aa3-f55e-4459-bff4-b0d40998b73c)

### Use Case

N/A

### Benefits

N/A

### Add ScreenShots

N/A

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by raju2109** [comment]
please assign me this issue under GSSoC '2024 i will enahance this page.

**Comment by PSS2134** [comment]
Please Make sure it matches website theme @MastanSayyad

**Comment by PSS2134** [comment]
> please assign me this issue under GSSoC '2024 i will enahance this page.

You can create other issues and start working on that

**Comment by MastanSayyad** [comment]
> Please Make sure it matches website theme @MastanSayyad 

Yes I will!
