### ISSUE TITLE
Doesn't Look Great

### ISSUE THREAD

**Issue by R1MO9** [HimanshuNarware/CareerZunction_Intern#48]
Description
The internship cards components does not looks great i can redesign and implement

**Screenshots**
![image](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/118689102/dcf27cdc-c1ba-4a73-950d-19394086eef1)

Example  Fill x { [x] }  into  bracket

- [ x ] I have checked the existing issues *
- [ x] I have read the Contributing Guidelines *
- [ x ] I have starred the repository *
- [ x ] Working under Gssoc24*

**Comment by R1MO9** [comment]
Please assign this to me under gssor'24 and add the labels

**Comment by spacedust26** [comment]
Hey @HimanshuNarware , could you please assign this task to enhance the cards under internship tab.  I'd like to redesign and bring about hover effect into it. I'm well versed in the required tech stack for this. Thank you !

**Comment by R1MO9** [comment]
@Chaitali-sonare assign me...

**Comment by IkramBagban** [comment]
Hello @Chaitali-sonare,

I noticed the issue titled "Doesn't Look Great" and I'm keen on improving the visual appeal as outlined. I have experience in UI/UX design and frontend development which could be very useful for enhancing the aesthetics and usability of the project.

Could you please assign this issue #48 to me under GSSOC'24? I am enthusiastic about making a significant visual improvement.

Thank you!

**Comment by HimanshuNarware** [comment]
@R1MO9  show me demo of your design

**Comment by R1MO9** [comment]
@HimanshuNarware 
<img width="960" alt="image" src="https://github.com/HimanshuNarware/CareerZunction_Intern/assets/118689102/e597bfef-ac8f-45ae-88bc-a4c10e8f5b2e">

customizable

**Comment by HimanshuNarware** [comment]
@R1MO9 does not look great, show me more design

**Comment by R1MO9** [comment]
@HimanshuNarware what changes you want?

**Comment by HimanshuNarware** [comment]
@R1MO9 changes that relative to the theme of website,

**Comment by R1MO9** [comment]
@HimanshuNarware ok then background gradient color change kar denge...

**Comment by HimanshuNarware** [comment]
@R1MO9  first show me demo.

**Comment by IP80808080** [comment]
👋 Hello! I'd be happy to help with this issue. Could you please assign it to me? Additionally, could you please label it for the appropriate level? Thank you! 🚀

**Comment by Chetanshinde123** [comment]
@HimanshuNarware Please assign to me I would like to work on it.
If any sample you want to be like please share it or I can do it on own.

**Comment by shashbh18** [comment]
@HimanshuNarware Please assign this issue to me .
