### ISSUE TITLE
can change color to a visible color

### ISSUE THREAD

**Issue by rawani123** [HimanshuNarware/CareerZunction_Intern#49]
![image](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/121213641/0a5f55eb-6a72-443a-85bc-dbb8dd84d38a)
we add a color which will more visible other than purple

**Comment by DevNandini02** [comment]
i would like to work on this. Please assign this task to me.

**Comment by HimanshuNarware** [comment]
@HimanshuNarware no it effect the theme of the website
