### ISSUE TITLE
[Bug]: Adjust the z-index of the menu buttons in mobile view

### ISSUE THREAD

**Issue by Riddhi162** [HimanshuNarware/CareerZunction_Intern#495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The z-index is faulty for all these buttons in the documentation page and other page sometimes they come below some other components.

### Expected behavior

This should be not the case its z-index should be the most

### Add ScreenShots

https://github.com/user-attachments/assets/7938f2e2-f43d-49a9-89c7-e90e63342bdf

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by PSS2134** [comment]
Please refer to the main link of website
