### ISSUE TITLE
[Feature Request]: Sponsors Section

### ISSUE THREAD

**Issue by Sharmaji513** [HimanshuNarware/CareerZunction_Intern#498]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Add a new "Sponsors" section to the website/application to acknowledge and thank sponsors who contribute to the project. This section will help showcase the support the project receives from individuals and organizations.

### Use Case

As a user of the website/application, I want to see a dedicated "Sponsors" section so that I can recognize and appreciate the organizations and individuals who support the project.

### Benefits

Recognize and thank sponsors for their support.
Encourage more sponsorships by showcasing current sponsors.

### Add ScreenShots

![2024-07-30-07-23-07](https://github.com/user-attachments/assets/9f4b45bc-4260-4287-b5ac-e3b4860ffa5b)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Sharmaji513** [comment]
@PSS2134  please assign me this feature
Thank you!

**Comment by PSS2134** [comment]
What sponsors will you be adding @Sharmaji513

**Comment by Sharmaji513** [comment]
we can consider reaching out to brands similar to those we had last year, as shown in the attached image. This includes companies like Quine, Vercel, Taskade, .xyz, and BlueLearn. The image highlights our previous sponsors and hiring partners, which we can use as a reference for potential new sponsors.

**Comment by PSS2134** [comment]
But we dont have sponsors for careerZunction @Sharmaji513
