### ISSUE TITLE
[Feature Request]: Create a Rate us section/ Page

### ISSUE THREAD

**Issue by sau-mili** [HimanshuNarware/CareerZunction_Intern#508]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Rate us on footer on click, directs to git repo. I wish to add a rate us section to add ratings, star rating to be precise

### Use Case

One can click on the rate us button, get directed to rate us page, and rate the page

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by PSS2134** [comment]
How will that work ? @sau-mili , will that be displayed somewhere

**Comment by sau-mili** [comment]
It will be a pop up, or a separate page as you wish. It will open on clicking rate us option in footer or navbar

**Comment by PSS2134** [comment]
We already have a feedback modal, where rating is included

> It will be a pop up, or a separate page as you wish. It will open on clicking rate us option in footer or navbar

We already have a feedback modal which has rating option included
