### ISSUE TITLE
[Feature Request]: Redesign the blog page

### ISSUE THREAD

**Issue by ayush-848** [HimanshuNarware/CareerZunction_Intern#510]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![image](https://github.com/user-attachments/assets/df7a5904-55ea-4abd-8bf3-4f379702c743)

### Use Case

I will change the layout and styling

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ayush-848** [comment]
@PSS2134 The page is of testimonial which is in the blog page.
Can I make it from scratch???

**Comment by PSS2134** [comment]
Already someone is working on this, you can work on other issues
