### ISSUE TITLE
FAQ and Footer Are Merging

### ISSUE THREAD

**Issue by lovelymahor** [HimanshuNarware/CareerZunction_Intern#511]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The FAQ section and footer on the website are currently merging, which creates visual clutter and usability issues. The feature request is to implement a solution that separates the FAQ section from the footer, ensuring they are distinct and visually separate.

### Use Case

Separating the FAQ and footer sections will improve the website's professional appearance and user experience, making it easier for users to navigate and find information without confusion.

### Benefits

What benefits would this feature bring to the project or community?

Improved User Experience - Enhances readability and usability.
Professional Appearance - Reflects a well-organized layout.
Increased Engagement - Encourages users to engage with content.
Better Navigation - Ensures important footer links are accessible.

### Add ScreenShots

![Screenshot (301)](https://github.com/user-attachments/assets/1629f718-6d0e-4e41-bbac-f6730ea99933)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by lovelymahor** [comment]
@HimanshuNarware 
I want to work on this issue. Also, please add the label GSSOC and the level that you find appropriate for this issue. thank you!

**Comment by PSS2134** [comment]
Its resolved I guess @lovelymahor
