### ISSUE TITLE
[Documentation Update]: CORRECTING THE IMAGE

### ISSUE THREAD

**Issue by Unnimaya6122004** [HimanshuNarware/CareerZunction_Intern#525]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

![Screenshot from 2024-08-05 06-06-50](https://github.com/user-attachments/assets/13bbac39-1c37-4246-9951-bd3433cfd3c5)

IMAGE CORRECTION

### Suggested Change

CORRECTION IMAGE

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by PSS2134** [comment]
Please refer to main link: https://career-zunction.vercel.app/intern @Unnimaya6122004
