### ISSUE TITLE
[Feature Request]: Add Newsletter Section to Footer

### ISSUE THREAD

**Issue by lovelymahor** [HimanshuNarware/CareerZunction_Intern#526]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Our website currently lacks a newsletter subscription section in the footer, missing an opportunity to engage visitors and grow our email list.

### Use Case

Allows users to easily subscribe to our newsletter, ensuring they stay informed about updates, events, and new content. Subscribers will receive timely notifications about new features and important announcements directly in their inboxes.

### Benefits

Increased Engagement: Keeps our audience engaged with regular updates.
Growing Email List: Builds a targeted audience for future communications.
Improved Communication: Fosters a stronger connection with our community.

### Add ScreenShots

![Screenshot (336)](https://github.com/user-attachments/assets/647efc12-83c9-45b4-a5f1-4ac279fc433a)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by PSS2134** [comment]
Dont create same issue multiple times @lovelymahor
