### ISSUE TITLE
Not GOOD for all screen size

### ISSUE THREAD

**Issue by Utsavladia** [HimanshuNarware/CareerZunction_Intern#530]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![image](https://github.com/user-attachments/assets/d7cafabd-2778-48ad-b291-54f02cc28efc)

### Use Case

This needed to be fixed to have a proper look on all screen sizes

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by PSS2134** [comment]
Refer to the main link of website
