### ISSUE TITLE
Design a New Logo and Add new Fevicon to The Website

### ISSUE THREAD

**Issue by RadhikaMalpani1702** [HimanshuNarware/CareerZunction_Intern#536]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @PSS2134 

I would like to design a New Logo and Add a new Fevicon to The Website as the current one looks too old and not attractive

![image](https://github.com/user-attachments/assets/13138915-c946-48f1-a75a-b8227e1b5bcf)

### Use Case

N/A

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by PSS2134** [comment]
Make it better than this @RadhikaMalpani1702
