### ISSUE TITLE
[Bug]: Footer Item not aligned properly

### ISSUE THREAD

**Issue by Sourabh782** [HimanshuNarware/CareerZunction_Intern#538]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The elements of footer are not aligned correctly and are disorted

### Expected behavior

all the elements of footer should be well aligned

### Add ScreenShots

![Screenshot 2024-08-05 205421](https://github.com/user-attachments/assets/63006077-e1c6-41a3-bed4-57f142020d53)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by PSS2134** [comment]
Please refer to the main link
