### ISSUE TITLE
[Feature Request]:  Addition of scroll to top button

### ISSUE THREAD

**Issue by Sourabh782** [HimanshuNarware/CareerZunction_Intern#539]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Addition of scroll to top button, to smoothly auto scroll to the top of page

### Use Case

Addition of scroll to top button will help users eg on intenrship page to quickly go to the top of page.

### Add ScreenShots

![Screenshot 2024-08-05 210356](https://github.com/user-attachments/assets/5e5caab5-26d9-4463-8bfa-fd6d0c8b6712)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by PSS2134** [comment]
Refer the main link of website
