### ISSUE TITLE
**Red Flags Regarding Page Responsiveness**

### ISSUE THREAD

**Issue by Che140401** [HimanshuNarware/CareerZunction_Intern#54]
Is your feature request related to a problem? Please describe.

- [ ] Navbar is not well responsive it is overlapping with home page

- [ ] Navbar menus are getting overlap and in mobile version is shown hidden

Describe the solution you'd like

- [ ] We will make it responsive navbar with hamburger menu which is responsive

** Add screenshot

![Screenshot 2024-05-11 130123](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/109230049/1b5fd1b8-e76e-44f3-8769-e8f8ec0e237e)

![Screenshot 2024-05-11 130403](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/109230049/2bd1e343-93f6-41a9-afac-6699cc1a8aa5)

![Screenshot 2024-05-11 130538](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/109230049/c604c50a-8e2d-4fe3-a698-a405469dce45)

We have to put overlay

![Screenshot 2024-05-11 130855](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/109230049/13429503-da49-4f48-bc21-dac3ed491b27)

Checklist
Example Fill x { [x] } into bracket

- [x ] I have checked the existing issues *
- [x ] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x ] Working under Gssoc24*

**Comment by HimanshuNarware** [comment]
@Che140401 someone is already working on this
