### ISSUE TITLE
add missing steps in  Documentation page and Give hovering effect on Navbar elements

### ISSUE THREAD

**Issue by AnkitMourya12** [HimanshuNarware/CareerZunction_Intern#542]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

In Dumentation page have some missing steps so i just add those missing step and
apart from this also Give hovering effect on navbar element.

### Use Case

just i adding this missing steps and makes interactive to user.

### Add ScreenShots

Ducumentation page:
<img width="955" alt="CZ3" src="https://github.com/user-attachments/assets/e833fceb-80c6-4d1c-8c7a-f56193eb9d85">

Navbar Hovering:
<img width="1070" alt="CZ2" src="https://github.com/user-attachments/assets/0ad259a7-4a7c-4ade-9bd5-b27c188715ff">

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by AnkitMourya12** [comment]
@PSS2134  can  you assign this issue to me under gssoc lables

**Comment by PSS2134** [comment]
Refer to main website @AnkitMourya12
