### ISSUE TITLE
[Bug]: Need Improvement in the Footer section

### ISSUE THREAD

**Issue by Ankur-Rai-19** [HimanshuNarware/CareerZunction_Intern#553]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

# Need improvement in the Footer section for the better look

![image](https://github.com/user-attachments/assets/223a7f5f-3da5-4286-97c1-41d4f2ff6a54)

### Expected behavior

The Footer should be more impressive and with the proper links availabe to it.

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by PSS2134** [comment]
Refer to the main website link @Ankur-Rai-19
