### ISSUE TITLE
[Feature Request]: Add Social icons in footer's link

### ISSUE THREAD

**Issue by zalabhavy** [HimanshuNarware/CareerZunction_Intern#554]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![image](https://github.com/user-attachments/assets/d6f6a5b0-2c93-40a8-9acf-5918d78167b1)
 

Here i want to add icon before text.

Like

![image](https://github.com/user-attachments/assets/5e38f63f-a4aa-49b2-b4e5-7b67cc477092)

### Use Case

Better UI.

### Benefits

USER ATTRACTION.

### Add ScreenShots

NA

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by zalabhavy** [comment]
@PSS2134 Please assign me this task !

Thank You !

**Comment by PSS2134** [comment]
Its already been done
