### ISSUE TITLE
Change Font Used on the landing page

### ISSUE THREAD

**Issue by harshmishra19** [HimanshuNarware/CareerZunction_Intern#56]
Is your feature request related to a problem? Please describe.

The current font used on the landing page is challenging to read, especially on smaller screens. It affects the user experience negatively, as it may discourage users from engaging with the content effectively.

Describe the solution you'd like

I would like to see an improvement in the font choice for the landing page. Specifically, I propose changing the font to a more legible option, such as "Roboto". This change will enhance readability, making the content more accessible and user-friendly across different devices and screen sizes. It will contribute positively to the overall user experience and increase user engagement with the website.

** Add screenshot

Checklist
Example Fill x { [x] } into bracket

- [x ] I have checked the existing issues *
- [ x] I have read the Contributing Guidelines *
- [ x] I have starred the repository *
- [x ] Working under Gssoc24*

**Comment by veera6513** [comment]
I would like to work on this issue, could you please assign it to me?

**Comment by HimanshuNarware** [comment]
@harshmishra19 share a screenshot

**Comment by harshmishra19** [comment]
In this section 
![Screenshot_20240512-073150_Chrome](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/115486960/23dc2d6f-5cb1-4024-8ffb-6ac4eddf2227)
 I would like to change the font to this 
![Screenshot_20240512-073115_Chrome](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/115486960/0aceac52-0f4b-4d1b-babf-65bbd7fe5a8f)
This gives it a more appealing look

**Comment by harshmishra19** [comment]
So I would like to work on this issue So can you please assign this issue to me

**Comment by HimanshuNarware** [comment]
@veera6513 does not look good, use another font family

**Comment by IkramBagban** [comment]
@HimanshuNarware @Chaitali-sonare please assign this to me. I'll add suitable fonts
