### ISSUE TITLE
Adding Icons in the navbar

### ISSUE THREAD

**Issue by harshmishra19** [HimanshuNarware/CareerZunction_Intern#57]
Is your feature request related to a problem? Please describe.

The current navbar lacks icons, which impacts its visual appeal and usability. Users might find it less engaging and intuitive to navigate through the website without visual cues provided by icons.

Describe the solution you'd like

I propose adding respective icons to the navbar to enhance its visual appeal and improve user navigation experience. These icons will align with the theme of the website and provide users with clear visual cues for each navigation option

** Add screenshot

![Screenshot 2024-05-11 080754](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/115486960/30fb78a8-191a-402b-9979-14adf0f55ece)

Checklist
Example Fill x { [x] } into bracket

- [ x] I have checked the existing issues *
- [x ] I have read the Contributing Guidelines *
- [ x] I have starred the repository *
- [ x] Working under Gssoc24*

**Comment by veera6513** [comment]
I would like to work on this issue, can you please assign it to me?

**Comment by HimanshuNarware** [comment]
@harshmishra19  already someone is working on this issue.
