### ISSUE TITLE
Missing Footer Section | Important links

### ISSUE THREAD

**Issue by ShrestyTyagi** [HimanshuNarware/CareerZunction_Intern#58]
Is your feature request related to a problem? Please describe.
The footer section is missing. It must contain all the important links.

Screenshot:
![Screenshot (597)](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/166687676/a350d79b-233c-417b-93b1-51dbfadfc14b)

I have read the Contributing Guidelines 
I have starred the repository 
I am working under Gssoc24

I request you to kindly assign me this issue @HimanshuNarware 
Please label this issue.

**Comment by HimanshuNarware** [comment]
@ShrestyTyagi  already someone is working on this issue.
