### ISSUE TITLE
Bug:Check now button on maximixe and minimze the screen

### ISSUE THREAD

**Issue by drick-infinity** [HimanshuNarware/CareerZunction_Intern#64]
**Describe the bug**
Here, a check now button see on minimizing the screen but remove on maximizing

**Expected behavior**
The check now button shown on both maximizing and minimizing

**Screenshots**
![Screenshot (31)](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/116994649/3ad7c362-e7fd-4f8e-a87f-a9a2c2732f36)
![Screenshot (32)](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/116994649/008a0a9c-0464-45dc-934b-0f4c36adf75b)

Example  Fill x { [x] }  into  bracket

- [ x] I have checked the existing issues *
- [ x] I have read the Contributing Guidelines *
- [ x] I have starred the repository *
- [x ] Working under Gssoc24*

**Comment by HimanshuNarware** [comment]
@drick-infinity  its feature. not a bug
