### ISSUE TITLE
[BUG] Social media handles at footer are not working 

### ISSUE THREAD

**Issue by Ayush170803** [HimanshuNarware/CareerZunction_Intern#66]
At Footer of the Page Social Media Handles are not redirecting to the mentioned handles so kindly provide the social media respective website links to fix this issue. Kindly assign me this issue, so i can work towards it under GSSOC'24. Thank You

https://github.com/HimanshuNarware/CareerZunction_Intern/assets/115927008/9c5c3328-5fd2-4889-85dc-6e1d917fd57c

- [x ] I have checked the existing issues *
- [ x] I have read the Contributing Guidelines *
- [x ] I have starred the repository *
- [x ] Working under Gssoc24*

**Comment by HimanshuNarware** [comment]
@Ayush170803   already someone is working on this issue.
