### ISSUE TITLE
feat/founder-and-mainter-section-UI

### ISSUE THREAD

**Issue by drick-infinity** [HimanshuNarware/CareerZunction_Intern#67]
Is your feature request related to a problem? Please describe.
better UI enhancement

Describe the solution you'd like
Better UI required using different css styles

Checklist
Example Fill x { [x] } into bracket

- [ ] I have checked the existing issues *
- [ ] I have read the Contributing Guidelines *
- [ ] I have starred the repository *
- [ ] Working under Gssoc24*

**Comment by HimanshuNarware** [comment]
@drick-infinity  already someone is working on this issue.
