### ISSUE TITLE
Add Favicon on the careerZunctino website app

### ISSUE THREAD

**Issue by HimanshuNarware** [HimanshuNarware/CareerZunction_Intern#9]
Add Favicon on the careerZunctino website app
Checklist
Example Fill x { [x] } into bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc24*

**Comment by m-tabish** [comment]
please assign me this issue

**Comment by m-tabish** [comment]
need the favicon file which is to be put up, can't find it in the codebase, kindly share or direct me.

**Comment by yashisrani** [comment]
@HimanshuNarware kindly assign me this issue under #gssoc'24 ..

**Comment by m-tabish** [comment]
I am working on this already and I just need the favicon to be shared @HimanshuNarware pls

**Comment by HimanshuNarware** [comment]
@m-tabish design a favicon yourself, according to the theme of the website, and share with me some designs Then I approve them. ok

**Comment by bk408** [comment]
Hello @HimanshuNarware I want to work on this issue. please assign me

**Comment by divyalaldinani** [comment]
hey if this issue is still pending, let me know if i can work on it @HimanshuNarware
