### ISSUE TITLE
internship card alignment 

### ISSUE THREAD

**Issue by NitinChakrawarti** [HimanshuNarware/CareerZunction_Intern#92]
In internships section, cards of internship are not aligned
properly.

**Expected behavior**
They are expected to  have same margin from both side.

**Screenshots**
![Screenshot 2024-05-12 211721](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/149225785/07b1695c-1054-4862-9575-6ebecb840dc1)

@HimanshuNarware  please assign this issue to me i want to work on this and make it more better under GSSoC24

**Comment by HimanshuNarware** [comment]
@NitinChakrawarti  someone already working on this issue
