### ISSUE TITLE
Add a light/dark theme toggle button on the navbar

### ISSUE THREAD

**Issue by karishmaaa101** [HimanshuNarware/CareerZunction_Intern#93]
Is your feature request related to a problem? Please describe.
The website would look even better if there would be a light/dark toggle theme.

![image](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/104766763/4d9966d6-1f58-4380-87ab-f446f349d5aa)

Checklist
Example Fill x { [x] } into bracket

- [ x ] I have checked the existing issues *
- [ x] I have read the Contributing Guidelines *
- [ x ] I have starred the repository *
- [ x ] Working under Gssoc24*

**Comment by HimanshuNarware** [comment]
@karishmaaa101 someone is already working on this issue.
