### ISSUE TITLE
Aligning the contents of 'about us' in home page

### ISSUE THREAD

**Issue by sooraj-reddy** [HimanshuNarware/CareerZunction_Intern#96]
**Describe the bug**
The contents in the 'about us' section of home page are not aligned with corresponding elements: icon, data, card.

**Expected behavior**
Equal and uniform between icons and data across all data-cards.

**Screenshots**
<img width="1412" alt="Screenshot 2024-05-12 at 11 38 55 PM" src="https://github.com/HimanshuNarware/CareerZunction_Intern/assets/108564825/16dfdf25-6318-43fd-ac8e-0a71c3ab6ef0">

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc24*

**Comment by Asin-Junior-Honore** [comment]
@sooraj-reddy , @HimanshuNarware  i would love to fix this issue please 🧑‍💻
